### ISSUE TITLE
How to use this lib on windows?

### ISSUE THREAD

**Issue by ghost** [trusch/libbcrypt#12]
I compile this lib and run test on windows, I get std::runtime_error:
generate hash...terminate called after throwing an instance of 'std::runtime_error'
  what():  bcrypt: can not generate salt
My compiler is MINGW 5.0

**Comment by kriive** [comment]
This happens because the lib is specifically written for *nix systems, where `/dev/urandom` is available. 
Even though the build succeeds, Windows does not provide `/dev/urandom` and salt generation fails in runtime throwing `std::runtime_error`.

Windows has a [native API for bcrypt](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/). It would be awesome to wrap it inside libbcrypt to get true cross-platform support.
I have very little spare time at the moment, but I promise I'll work on this as soon as I can. (Can't promise any ETA).

You can find more infos in closed issue no #9.
