### ISSUE TITLE
Potential for memory leak with use of strdup?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [trusch/libbcrypt#14]
Noticed this call in wrapper.c when trying to make it work with windows.
(Had to change to a safer function name for w/e reason as the POSIX name was depecrated.).
Is there a potential memory leak with the use of strdup?

Documentation says need to free the return value.
https://en.cppreference.com/w/c/experimental/dynamic/strdup

**Comment by kriive** [comment]
If you are referring to `char *__crypt_gensalt_ra(...)`,
strdup() return pointer is used as return value of that function.

The user has to free the return value of `crypt_gensalt_ra(...)`, otherwise memory leaks could occur, yes. Did you notice a call to `crypt_gensalt_ra()` without freeing result?

**Comment by kriive** [comment]
@trusch I propose to close this issue, because it is not strictly related to libbcrypt, but to original C implementation.
